/*******************************************************************************
 * Copyright (c) 2012 Gerd Wuetherich (gerd@gerd-wuetherich.de).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Gerd Wuetherich (gerd@gerd-wuetherich.de) - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.02 at 10:11:51 PM MEZ 
//

package com.wuetherich.osgi.ds.annotations.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.javakontor.osgi.ds.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Component_QNAME = new QName("http://www.osgi.org/xmlns/scr/v1.1.0", "component");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * org.javakontor.osgi.ds.xml
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Tcomponent }
   * 
   */
  public Tcomponent createTcomponent() {
    return new Tcomponent();
  }

  /**
   * Create an instance of {@link Tproperties }
   * 
   */
  public Tproperties createTproperties() {
    return new Tproperties();
  }

  /**
   * Create an instance of {@link Tproperty }
   * 
   */
  public Tproperty createTproperty() {
    return new Tproperty();
  }

  /**
   * Create an instance of {@link Timplementation }
   * 
   */
  public Timplementation createTimplementation() {
    return new Timplementation();
  }

  /**
   * Create an instance of {@link Treference }
   * 
   */
  public Treference createTreference() {
    return new Treference();
  }

  /**
   * Create an instance of {@link Tprovide }
   * 
   */
  public Tprovide createTprovide() {
    return new Tprovide();
  }

  /**
   * Create an instance of {@link Tservice }
   * 
   */
  public Tservice createTservice() {
    return new Tservice();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Tcomponent }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://www.osgi.org/xmlns/scr/v1.1.0", name = "component")
  public JAXBElement<Tcomponent> createComponent(Tcomponent value) {
    return new JAXBElement<Tcomponent>(_Component_QNAME, Tcomponent.class, null, value);
  }

}
