//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:39:31 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.osgi.org/xmlns/scr/v1.1.0")
package com.wuetherich.osgi.ds.annotations.xml;
