//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.02 at 10:11:51 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.osgi.org/xmlns/scr/v1.1.0", xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.osgi.org/xmlns/scr/v1.1.0", prefix = "scr") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wuetherich.osgi.ds.annotations.xml;

