//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 06:39:31 AM CET 
//


package com.wuetherich.osgi.ds.annotations.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tconfiguration-policy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Tconfiguration-policy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="optional"/>
 *     &lt;enumeration value="require"/>
 *     &lt;enumeration value="ignore"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Tconfiguration-policy")
@XmlEnum
public enum TconfigurationPolicy {

    @XmlEnumValue("optional")
    OPTIONAL("optional"),
    @XmlEnumValue("require")
    REQUIRE("require"),
    @XmlEnumValue("ignore")
    IGNORE("ignore");
    private final String value;

    TconfigurationPolicy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TconfigurationPolicy fromValue(String v) {
        for (TconfigurationPolicy c: TconfigurationPolicy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
