/*******************************************************************************
 * Copyright (c) 2015 Gerd Wütherich.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    Gerd Wütherich (gerd@gerd-wuetherich.de) - initial API and implementation
 ******************************************************************************/
package org.eclipse.pde.ds.annotations;

import org.osgi.service.component.annotations.Component;

public interface Constants {

  /** - */
  final String BUNDLE_ID                                      = Constants.class.getPackage().getName();

  /** - */
  final String BUILDER_ID                                     = Constants.class.getPackage().getName()
                                                                  + ".dsAnnotationBuilder";

  /** - */
  final String NATURE_ID                                      = Constants.class.getPackage().getName()
                                                                  + ".dsAnnotationNature";

  /** - */
  final String DS_ANNOTATION_PROBLEM_MARKER                   = Constants.class.getPackage().getName()
                                                                  + ".dsAnnotationProblem";

  /** - */
  final String PREF_DS_VERSION                                = Constants.class.getPackage().getName()
                                                                  + ".componentversion";

  /** - */
  final String PREF_MARK_COMPONENT_DESCRIPTOR_AS_DERIVED      = Constants.class.getPackage().getName() + ".derived";

  /** - */
  final String BUNDLE_HEADER_SERVICE_COMPONENT                = "Service-Component";

  /** - */
  final String COMPONENT_DESCRIPTION_FOLDER                   = "OSGI-INF";

  /** - */
  final String DS_ANNOTATION_PACKAGE                          = Component.class.getPackage().getName();

  /** - */
  final String DS_ANNOTATION_BUILDER_GENERATED_COMMENT_REGEXP = "(Generated by DS Annotation Builder \\[)(.*)(\\])";

  /** - */
  final String DS_ANNOTATION_BUILDER_GENERATED_COMMENT        = "<!--Generated by DS Annotation Builder [%s]-->\n";
}
